name: BobBack CI

on: [push]

jobs:
  build_Back:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Build & Test
        working-directory: ./back
        run: mvn clean install

      - name: Artefact coverage
        uses: actions/upload-artefact@v4
        with:
          name: coverage jacoco
          path: ./back/target/site/jacoco/index.html

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push on Dockerhub
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: adrienpiombini/p10_bob_application:backend
