name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: cd front
      - run: ls
      - run: |
          ls ${{ github.workspace }}

# - run: npm install
# - run: npm run build --if-present
# - run: npm test
